appveyor.yml
scripts/prepare-appveyor.cmd
src/heif_encoder_x265.cc

This will help to prevent regressions in the future.
Fixes #10

CI: Build libde265/x265 and plugins on Windows

---

.travis.yml
scripts/install-ci-linux.sh
scripts/prepare-ci.sh
scripts/run-ci.sh

We had reports of linker errors with MinGW in the past (e.g. #28), so also test building on that platform to prevent future regressions.

CI: Test building with MinGW.

---

configure.ac
examples/CMakeLists.txt
examples/encoder_jpeg.cc
examples/encoder_jpeg.h
examples/heif_enc.cc

@hmage, @Whissi could you please check if building against your libjpeg-turbo 2.0 installations works with these changes?

Support building against libjpeg-turbo 2.0 (fixes #70).

---

examples/heif_enc.cc

add color profile embedding example if input jpeg has an embedded color profile. This will use heif_image_set_raw_color_profile .

add color profile embedding example if input jpeg has an embedded color profile

---

.gitignore
scripts/run-ci.sh
tests/Makefile.am
tests/test-race.go

To prevent regressions of #147.

CI: Run race tester as part of Travis GO job.

---

scripts/install-emscripten.sh
scripts/run-ci.sh

Fixes CI errors while installing the SDK

The Emscripten SDK is now hosted on GitHub.

---

scripts/install-ci-osx.sh

This fixes an error where the wrong version of ruby is used.

CI: Update homebrew before installing / removing packages (OSX).

---

libheif/heif_cxx.h

Some functions that I needed were missing from the C++ header.

Add some more functions to the cxx header

---

README.md

The sample codes seems to be out of date with the current api for `heif_context_encode_image`

Update README to latest api

---

libheif/heif_colorconversion.cc

Fix clang -Wpotentially-evaluated-expression warnings on typeid()
arguments that contain function calls. Here is an example of the warning
message:
heif_colorconversion.cc:2952:33: warning: expression with side effects
will be evaluated despite being used as an operand to
'typeid' [-Wpotentially-evaluated-expression]
std::cerr << "> " << typeid(*op).name() << "\n";
^
The actual warning fix is to pass to typeid() an expression that does
not call any function. Also modify related code to maintain a consistent
style.

Fix -Wpotentially-evaluated-expression warnings

---

libheif/heif_cxx.h

Add a few missing inline to fix ODR violation.

Add missing inline.

---

libheif/heif_encoder_aom.cc

We need to call aom_codec_get_cx_data() after each aom_codec_encode()
call. In real-time mode, the output packet is generated after the first
aom_codec_encode() call. Apparently that output packet is deleted when
the second aom_codec_encode() call (with the NULL second argument) is
invoked.
Fix https://github.com/strukturag/libheif/issues/350.

Call aom_codec_get_cx_data() after encode_frame()

---

libheif/heif_encoder_aom.cc

This PR improves the error reporting of encoding with aom and thereby resolves assertion failures when encoding large images on a Raspberry Pi 4B (with only 4GB ram available).
To summarize, ~the `aom_log_error` function (similar to the [`die_codec`](https://aomedia.googlesource.com/aom/+/6514dccc195aa95d45fe156fac77ff57627975ff/common/tools_common.c#71) example) was introduced for logging aom encoding errors and~ (potentially) reachable `assert(false)` calls are removed in favor of returning appropriate errors.

Improve aom encode error reporting

---

libheif/heif_image.cc

Update plane dimensions in extend_to_size

---

third-party/dav1d.cmd
third-party/rav1e.cmd

- Updates dav1d.cmd to use version 0.8.1 instead of 0.7.1
- Updates rav1e.cmd to use the 0.3 maintenance branch instead of version 0.3.4

3rd party: Update dav1d to 0.8.1 and rav1e to 0.3 maintenance branch

---

CMakeLists.txt

@fancycode FYI, since you authored https://github.com/strukturag/libheif/pull/294

Make minimum CMake version match actual requirements

---

scripts/cpplint.py
scripts/pre-commit.hook
scripts/run-ci.sh

Support both python and python3 for running cpplint.

---

third-party/dav1d.cmd

See https://code.videolan.org/videolan/dav1d/-/tags/0.8.2

3rd party: Update dav1d to 0.8.2

---

libheif/heif_encoder_aom.cc

Change speed integer maximum

---

.github/workflows/fuzzer.yml
scripts/run-ci.sh

Fixes error in fuzzer CI action.

CI: Fix fuzzer build errors.

---

libheif/CMakeLists.txt

Makes it equivalent w/ autotools install

cmake: install only public headers

---

libheif/heif_encoder_aom.cc

This allows callers to pass custom options to the AOM encoder by adding
an 'aom:' prefix to the option name.
Th custom options will be applied after libheif configures the default
options because they can override the values that were set.
The x265 encoder already has a similar feature with the 'x265:' prefix.
Resolves #596

Add support for the AOM key=value API

---

.clang-tidy
.github/workflows/clang.yml
examples/encoder.h
examples/encoder_png.cc
examples/encoder_y4m.cc
examples/heif_enc.cc
examples/heif_test.cc
examples/heif_thumbnailer.cc
libheif/bitstream.cc
libheif/bitstream.h
libheif/box.cc
libheif/box.h
libheif/error.cc
libheif/error.h
libheif/heif.cc
libheif/heif_avif.cc
libheif/heif_avif.h
libheif/heif_colorconversion.cc
libheif/heif_colorconversion.h
libheif/heif_context.cc
libheif/heif_context.h
libheif/heif_cxx.h
libheif/heif_encoder_x265.cc
libheif/heif_file.cc
libheif/heif_file.h
libheif/heif_image.cc
libheif/heif_image.h
libheif/heif_plugin.h
libheif/logging.h
scripts/run-ci.sh

This can help finding some errors / possible optimizations.

CI: Run clang-tidy

---

libheif/heif_context.cc

I propose here to reuse an existing m_max_decoding_threads, that, if set to 0, effectively reverts to the same effect as if the library was compiled without ENABLE_PARALLEL_TILE_DECODING . That setting is context-dependent and allows both threaded and non-threaded encoding to coexist in a single application.

refs #635: second attempt to extend API to disable MT decoding

---

libheif/heif_emscripten.h
scripts/install-emscripten.sh

JS: Fix copying of strided image data.

---

CMakeLists.txt
libheif/CMakeLists.txt
libheif/box.cc
libheif/box.h
libheif/heif_context.cc
libheif/heif_context.h
libheif/heif_file.cc
libheif/heif_file.h

@farindk Is this the kind of approach you had in mind for the "internal" implementation?
Clearly this is not complete, and will need significant cleanup, just looking for comments on the tie-in.

uncompressed: draft work on uncompressed decoder

---

libheif/uncompressed_image.cc

This enables correct rendering of the  `uncC_2_rgb_planar_tiled.heif` and `uncC_3_rgb_interleaved_tiled.heif` samples.

uncompressed: add tiling support for planar and interleaved images

---

libheif/uncompressed_image.cc

Also renames Component_x to Component_Type_x to allow easier distinguish from Components
Also removes an obsolete comment on component ordering.

uncompressed: additional component types

---

libheif/box.cc
libheif/box.h

This supports the implementation of region annotations.
See ISO/IEC 23008-12:2022(E) Section 6.5.20.

udes: implementation for user description property

---

cmake/modules/FindAOM.cmake

Resolves #720.
Instead of checking the version, this checks for a required feature.

cmake: check we found a working version of AOM

---

libheif/Makefile.am
libheif/color-conversion/colorconversion.cc
libheif/color-conversion/monochrome.cc
libheif/color-conversion/rgb2rgb.cc
libheif/color-conversion/rgb2rgb.h
libheif/color-conversion/rgb2yuv.cc
libheif/color-conversion/rgb2yuv_sharp.cc
libheif/color-conversion/rgb2yuv_sharp.h
libheif/color_conversion_fuzzer.cc
libheif/heif.cc
libheif/heif_image.cc
tests/conversion.cc

Add sharp yuv support for planar rgb and higher bit depths.
Improve tests: check that output image has the expected planes/bit depths etc., and check psnr after roundtrip when possible. 
Fix makefile build.

Improve sharp yuv support and tests.

---

libheif/color-conversion/rgb2yuv_sharp.cc
tests/conversion.cc

Fix sharpyuv conversion width depth changes.

---

libheif/heif.cc

The debugger was showing this field as using uninitialized memory,

Set the heif_color_conversion_options version field

---

libheif/heif.cc
libheif/heif.h

Also add mif2 brand as "maybe"
This avoids use of deprecated API.

switch to brand2 for file type checking

---

libheif/heif.cc
libheif/heif.h

A little contribution to recognise JPEG in HEIF.
Feel free to close if this dupes existing work...

jpeg: brands

---

libheif/box.cc
libheif/box.h
libheif/file.cc
libheif/heif.h

Also cleans up some existing code that was being added to, for consistency.
Resolves #884

Implement 1pic brand

---

CMakeLists.txt
examples/encoder.cc
examples/encoder_jpeg.cc
examples/heif_convert.cc
examples/heif_enc.cc
examples/heif_info.cc
examples/heif_test.cc
examples/heif_thumbnailer.cc
libheif/bitstream.h
libheif/box.cc
libheif/box.h
libheif/context.cc
libheif/error.h
libheif/file.h
libheif/heif.cc
libheif/logging.h
libheif/plugin_registry.cc
libheif/plugins/decoder_aom.cc
libheif/plugins/decoder_dav1d.cc
libheif/plugins/decoder_jpeg.cc
libheif/plugins/decoder_libde265.cc
libheif/plugins/encoder_aom.cc
libheif/plugins/encoder_jpeg.cc
libheif/plugins/encoder_kvazaar.cc
libheif/plugins/encoder_mask.cc
libheif/plugins/encoder_rav1e.cc
libheif/plugins/encoder_svt.cc
libheif/plugins/encoder_uncompressed.cc
libheif/plugins/encoder_x265.cc
libheif/security_limits.h

This appears to be left over from the autoconf build system

remove config.h entries

---

libheif/color-conversion/rgb2yuv.cc
tests/conversion.cc

Fix bug in Op_RRGGBBxx_HDR_to_YCbCr420.

Add some tests for nclx conversion.

---

libheif/plugins/encoder_aom.cc

In libaom v2.0.2 or older, the first frame is incorrectly using a qindex (quantizer index) lower than the provided cq_level.
This bug was fixed by the libaom changelist
https://aomedia-review.googlesource.com/c/aom/+/132881. The bug fix was cherry-picked to the libaom 2.0.x release branch ("applejack"), but v2.0.3 was never released.
Fix https://github.com/strukturag/libheif/issues/895.

Work around a qindex bug in libaom v2.0.2 or older

---

libheif/box.cc

box: add missing break in switch

---

libheif/color-conversion/colorconversion.cc

Fixes #950. Happy for feedback.

Add init_ops mutex

---

CMakeLists.txt
examples/CMakeLists.txt
libheif/CMakeLists.txt

CMake: bump min required, use imported targets

---

libheif/plugins/encoder_openjpeg.cc

See https://github.com/uclouvain/openjpeg/pull/1383

Remove deprecated OpenJPEG struct member

---

examples/heif_convert.cc
examples/heif_enc.cc
libheif/context.cc

See e.g. https://jpeg.org/jpeg2000/

Use standard name for JPEG 2000

---

libheif.pc.in

remove obsolete pkg_config variables

---

examples/encoder_png.cc

exif: protected against large offset values

---

libheif/heif_items.h

This is some documentation salvaged from #1027.

doc: minor api documentation update for items API

---

libheif/heif.h

No code changes, just a tidy up of existing entries.

docs: minor doxygen update

---

libheif/Doxyfile.in
libheif/heif_items.h

Also fixes a couple of doxygen problems and includes more documentation.
No code changes.

docs: add new items API to doxygen configuration

---

libheif/plugins/encoder_kvazaar.cc

kvazaar: protect against unexpected chroma values

---

CMakeLists.txt

ffmpeg: added reference to "avutil"

---

examples/heif_convert.cc

Fix potential memory leak in file heif_convert.cc

Fix potential memory leak in file heif_convert.cc

---

examples/heif-convert.1

Minor update suggested at #1150 and an extra cut-n-paste fix.
Resolves #1150.
A full rework of the man page can come after #985

doc: explain quality a bit more for heif-convert

---

examples/decoder_tiff.cc

Fixes #1235 
@kmilos could you please test this? Thanks!

tiff: Fix wrong type for "seekTIFF" function.

---

examples/encoder.cc
examples/encoder.h
examples/encoder_jpeg.cc
examples/encoder_jpeg.h
examples/encoder_png.cc
examples/encoder_png.h
examples/encoder_y4m.cc
examples/encoder_y4m.h
examples/heif_dec.cc

Update some out-of-date headers. No code changes.

examples: fix header doc

---

README.md
libheif/api/libheif/heif.h
libheif/codecs/uncompressed.h

doc: fix some uncompressed codec spec references

---

libheif/context.cc

Inspired by today's discussion on TB-20 telecon.

clarify pitm error

---

libheif/api/libheif/heif_sequences.h

I'm still reviewing the heif_track_builder.

typo: builer -> builder
