strukturag/libheif

.travis.yml, CPPLINT.cfg, autogen.sh, examples/encoder_jpeg.h, examples/encoder_png.h, scripts/cpplint.py, scripts/install-ci.sh, scripts/pre-commit.hook, scripts/prepare-ci.sh, scripts/run-ci.sh, src/heif.cc
For now only enable `build/include_what_you_use` to make sure necessary headers get included. The checks will be extended in the future to ensure a consistent style.
Also contains a pre-commit hook (installed by `autogen.sh`) to check files before they get committed.
=> Add CPPLINT static code analysis

examples/encoder_jpeg.cc, examples/encoder_png.cc
fixing to build error on macOS high sierra.
- bool & boolean confusion on calling jpeglib functions
- errno variables need errno.h
----
% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
=> build for macOS high sierra.

src/heif_decoder_libde265.cc
The current syntax fails to build with Visual Studio 2017. This patch fixes the build.
=> Use syntax that is supported with Visual Studio.

src/heif_plugin_registry.cc
Without this, on a sufficiently new clang, with enough warnings turned on, you get a compilation error:
https://gist.github.com/reaperhulk/17f35e9410177970677bb9a30958f884
=> Mark operator() on comparator function as const

examples/Makefile.am
I always do VPATH builds, and libheif was not building correctly because some files were in the src dir and other in the build dir, and the current automake code was not properly looking in both.
This fixes it.
=> Fix VPATH (out-of-tree) builds.

src/file-fuzzer.cc, src/heif_image.cc
For GIMP, we need libheif to build for Windows. Here are the commits which resulted after failing to build (now it builds fine).
=> Win32 build

configure.ac, src/Makefile.am
This should fix the error reported in #28.
@Jehan: could you please check if this fixes the error you were getting?
=> Pass "-no-undefined" when linking with MinGW.

libheif.pc.in
During development of [HEIF plug-in for darktable](https://gitlab.websupport.sk/peter.kovar/darktable/tree/HEIF) I've noticed incorrect library search path order.
=> Modified the search order: directory first, then library

libheif/heif_file.cc
Previously it only failed when trying to read from the `std::ifstream`.
=> Handle error when file could not be opened.

examples/heif-test.go, go/heif/heif.go
- Register another heif image format header
- Remove debug code
- Don't pre- _and_ suffix error variables
- Better output formatting of example
- Goify names (remove underscores, uppercase `ID`, etc.)
=> Various improvements to the updated Go library and example app

go/heif/heif.go
This fixes an issue where struct members were passed to external C
functions after which the struct was no longer referenced.
As described in the docs of runtime.SetFinalizer, this would allow
the Go garbage collector to run every finalizer associated with the
struct (as it will no longer be used). Unfortunately, as we bound
a finalizer to free every C-allocated struct member, those
finalizers were run, freeing the struct members too early.
=> go: Fix C-allocated struct members being freed too early

CMakeLists.txt, Makefile.am, configure.ac, gdk-pixbuf/CMakeLists.txt, gdk-pixbuf/Makefile.am, gdk-pixbuf/pixbufloader-heif.c, scripts/install-ci-linux.sh, scripts/prepare-ci.sh
Providing a gdk-pixbuf loader module means applications such as `gpicview` and `pcmanfm` automatically gain HEIF support.
There are probably some improvements to be made, it would be especially nice to use the embedded thumbnails, but application code doesn't seem to reliably indicate to gdk-pixbuf that a thumbnail could be returned
=> Implement gdk-pixbuf loader

gnome/Makefile.am
Do not install arch independent files into prefix, which can be e.g.
/usr/x86_64-pc-linux-gnu for cross environments so instead of the files
landing in the arch independent /usr/share they wrongly get installed into
the arch dependent /usr/x86_64-pc-linux-gnu/share location.
=> fix shared install on cross environments

README.md
When I visited this repository I just wanted to build the project to use the recent master. It could be a good introduction for new visitors to have an easy entry with build instructions for macOS. Hopefully working for the majority of macOS users. Tested on macOS 10.14.6  and Homebrew 2.1.11-107-g39dabb4 (both newest on 21.09.2019).
=> Add macOS build instructions

gdk-pixbuf/Makefile.am
Without `-module` flag libtool generats `.dylib` extension and pixbuf expects `.so`
=> Add `-module` flag to get correct extension on macOS

gdk-pixbuf/pixbufloader-heif.c
1. If new size was requested and image was scaled - redefine width/height to the new values
2. Do not duplicate `heif_image_get_width` for no reason
3. Send image width/height to the size_func call as other pixbuf loaders doing.
This fixing `gdk_pixbuf_new_from_file_at_size` for me.
=> Fix for the gdk pixbuf `gdk_pixbuf_new_from_file_at_size` call

CMakeLists.txt, examples/CMakeLists.txt, examples/heif_enc.cc, gdk-pixbuf/CMakeLists.txt, libheif/CMakeLists.txt, libheif/box.cc, libheif/heif_encoder_x265.cc
This fixes building libheif with gcc 9.2.1.
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`
=> Several fixes to build libheif

libheif/bitstream.cc, libheif/bitstream.h, libheif/box.cc
Thank you for creating and maintaining this very useful library.
I've been reviewing the recently-added AVIF logic and ran into this problem with a possible integer overflow. It looks like all the existing bitstream logic was expecting/able to handle 64-bit integers apart from one method signature, which this PR should hopefully fix.
=> Ensure 64-bit int bitstream ranges, prevents possible overflow

libheif/heif_encoder_aom.cc
Commented out for now; happy to delete these should that be more preferable.
=> Remove debugging statements from AOM encoder

libheif.pc.in
This allows for compile-time feature detection of AOM, which will be very useful for consumers of this library, especially where h265 support must be disabled e.g. due to patent issues.
=> Expose have_aom status via pkg-config variables

examples/CMakeLists.txt
I have PNG and JPEG installed from brew on macos, so the headers/libs are not in default search folders. I have adjusted CMake so that the examples build.
=> Fix CMake builds for examples where jpeg/png is not in normal include

gdk-pixbuf/CMakeLists.txt
Fix linking gdk-pixbuf against libheif
=> cmake: Fix linking gdk-pixbuf against libheif

CMakeLists.txt, appveyor.yml, cmake/modules/FindLibde265.cmake, cmake/modules/FindX265.cmake, cmake/modules/LibFindMacros.cmake, examples/CMakeLists.txt, gdk-pixbuf/CMakeLists.txt, libheif/CMakeLists.txt
This involves the following changes:
- Use Triton's LibFindMacros to drop pkg-config to an indirect
dependency
- Use LibFindMacros to find libde265 and x265
- Relative-ize gdk-pixbuf install path so as to not break down when
installing as non-admin user
- Fix inclusion of libjpeg-turbo and feature testing
- Enable examples by default in CMake
- Fix missing bits for Appveyor CI: scripts and inclusion variables
The change involving gdk-pixbuf is necessary in Linux and macOS when the library isn't directly installed to `/usr/`. I slipped it here because it's part of my recent [merge request in Krita](https://invent.kde.org/kde/krita/-/merge_requests/258).
=> Allow libheif to be compiled in Windows using MinGW

libheif/heif_encoder_aom.cc
aom_encode_image() should clear encoder->compressedData before getting
compressed packets. This fixes https://github.com/strukturag/libheif/issues/279.
Also remove an unnecessary (uint8_t*) cast for the second argument to memcpy().
=> Clear encoder->compressedData in aom_encode_image

libheif/heif_encoder_rav1e.cc, third-party/rav1e.cmd
The speed value of 5 is very slow for rav1e. Increasing speed to 8 does not compromise much on quality but offers great speed improvements. Ref: https://preview.redd.it/tu4bwpgyco241.png?width=827&format=png&auto=webp&s=e4f0b9cc8f70bf93a0d1ddbb3cb413747fd5b130 this graph from this post: https://www.reddit.com/r/AV1/comments/e65dhl/libaom_vs_rav1e_vs_svtav1_test_results_with/
=> Default speed value for rav1e is increased to 8

libheif/heif.cc, libheif/heif.h, libheif/heif_api_structs.h, libheif/heif_context.cc
This PR will make the `heif_context` for the `heif_context_get_encoder` and `heif_context_get_encoder_for_format` mandatory again. There is (now was) a comment in the `heif.h` header file with a question why the context was necessary. The context should be passed to allow storing the error message. We could use that to report an error message in our application when we use the C API. The current code now prints the following error message in the @ImageMagick code when the encoder could not be found:
`magick: Success `test.avif' @ error/heic.c/IsHeifSuccess/134.`
This is happening because the error has `kSuccess` as the error message instead of the correct error message.
This PR is split into multiple commits and also removes the unused `context` field from `heif_encoder`. If you would …
=> Make heif_context mandatory again.

libheif/heif_context.cc
Prevents the following compiler warnings:
```
heif_context.cc: In function 'std::shared_ptr<heif::HeifPixelImage> create_alpha_image_from_image_alpha_channel(std::shared_ptr<heif::HeifPixelImage>)':
heif_context.cc:1623:48: warning: conversion from 'int' to 'uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
1623 |   alpha_image->fill_new_plane(heif_channel_Cb, half_range, chroma_width, chroma_height, bpp);
|                                                ^~~~~~~~~~
heif_context.cc:1624:48: warning: conversion from 'int' to 'uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
1624 |   alpha_image->fill_new_plane(heif_channel_Cr, half_range, chroma_width, chroma_height, bpp);
|                                                ^~~~~~~~~~
```
=> Silence possible integer conversion warnings

libheif/heif_encoder_aom.cc
Until issue #288 is fixed, we have to live with using a hardcoded value
of color_range in the aom encoder. It is more common for images to be
full range than limited range. So set color_range to full range (1) in
aom.
=> Set color_range to full range (1) in aom

libheif/heif.cc
I have error with gcc 11.0. _MSC_VER should be less than 1900
```
heif.cc: In function 'void heif_context_debug_dump_boxes_to_file(heif_context*, int)':
heif.cc:330:18: error: 'write' was not declared in this scope; did you mean 'fwrite'?
330 |   auto written = write(fd, dump.c_str(), dump.size());
|                  ^~~~~
|                  fwrite
```
=> New defined _MSC_VER for GCC

libheif/heif_encoder_x265.cc
This is equivalent to the original code and matches the corresponding if
statements in aom_encode_image() and rav1e_encode_image().
=> Merge nested if statements in x265_encode_image()

libheif/heif_context.cc
No need to call set_default() on newly constructed color_profile_nclx
objects because the color_profile_nclx constructor calls set_default().
=> Omit set_default call on new color_profile_nclx

libheif/CMakeLists.txt, libheif/Makefile.am
The next version of rav1e (v0.4.0) will require this linker flag. Adding it prevents the following linker errors:
```
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `dladdr'
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `dlsym'
```
Linking against the current v0.3.4 of rav1e works with and without this change so it's both backwards and forwards compatible.
=> rav1e: ensure linker knows of dl dependency

.github/workflows/build.yml, CMakeLists.txt, README.md, cmake/modules/FindDav1d.cmake, configure.ac, libheif/CMakeLists.txt, libheif/Makefile.am, scripts/install-ci-linux.sh, scripts/prepare-ci.sh, scripts/run-ci.sh, third-party/dav1d.cmd
This will help in adding support for dav1d when packaging.
Updated the script to build custom version in "third-party" folder so it can be used through "pkg-config" instead of relying on hardcoded folder names.
=> Use "pkg-config" to detect if dav1d is available.

libheif/heif.cc
The image width was being returned instead of the height.
=> Fix heif_image_get_primary_height for interleaved RGB images

libheif/heif_encoder_aom.cc
Set cfg.g_limit to 1 to make the libaom encoder set still_picture and
reduced_still_picture_header to 1 in the AV1 sequence header OBU.
Empirically this saves six bytes in image size.
=> Set still_picture to 1 in AV1 sequence header OBU

CMakeLists.txt
This patch allows using libheif included in another CMake project.
=> Use PROJECT_SOURCE_DIR for CMAKE_MODULE_PATH

libheif/box.cc
The reading of the clap values were reversed in the Fraction constructor.
=> Fix clap parse

libheif/heif.cc
The warnings were:
libheif/heif.cc:1543:25: error: ‘maximum’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1543 |           (have_maximum && value > maximum)) {
|           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
libheif/libheif/heif.cc:1542:25: error: ‘minimum’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1542 |       if ((have_minimum && value < minimum) ||
|           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
---------------------------------------------
Note 1: I didn't have this issue previously with Fedora 31 (last builds maybe a few weeks ago though), but I just updated to Fedora 33 with gcc version 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC) and now I got these warnings.
Note 2: the warnings/errors …
=> Fix warnings treated as errors.

libheif/heif_encoder_aom.cc
This PR fixes building of this library with Visual Studio 2015. Without this include it reports an error about `std::max`.
=> Added include to fix building with VS2015.

third-party/rav1e.cmd
It sidetracks the problem of linking the static library without using the information provided by the pkg-config file.
Discovered when investigating https://github.com/lu-zero/cargo-c/issues/181
=> Make the vendored rav1e completely static

examples/CMakeLists.txt
This makes install behaviour equivalent to autotools if examples are enabled
Also, use PNG on MinGW (both libpng and winpthreads are available)
=> Install examples when building w/ CMake

libheif/heif_encoder_aom.cc
The kParam_tune_valid_values array was missing the NULL pointer that
marks the end of the list.
=> Fix an out-of-bounds read with the AOM tune parameter array

cmake/modules/FindRav1e.cmake
Useful if the user wants to distribute the `rav1e.dll` along with `heif.dll`
=> Add rav1e.dll to make cmake find rav1e on MSVC targets

appveyor.yml
I rewrote the AppVeyor configuration file to modernize the build process a bit:
- Updates environment to the Visual Studio 2019 image (running on Windows Server 2019)
- Use [vcpkg](https://github.com/microsoft/vcpkg) for installing dependencies, using the latest available versions
- Caches the vcpkg depenencies for faster consecutive builds
- Remove x86 job, add arm64 job
- Publish individual .exe artifacts
The first build will be slow, because all the dependencies will need to be build, but all builds after that will be significantly faster because libde265, x265 and dav1d are cached with vcpkg.
The AppVeyor setup now doesn't depend on any external scripts, so `scripts\prepare-appveyor.cmd` can be deleted or renamed.
=> Refactor AppVeyor configuration

appveyor.yml
Currently the build `.exe` files are separately uploaded to AppVeyor as artifacts, but since libheif is build dynamically those are useless without the `.dll` library. This PR fixes that.
Small follow up on #470.
=> AppVeyor: Also publish build .dll files separately as artifacts

libheif/heif_decoder_aom.cc
Errors that occur in the aom decoder currently return a generic "Success" message.
```sh
$ heif-convert testimage.avif out.png
File contains 1 images
Could not decode image: 0: Invalid input: Unspecified: Success
```
To make such problems easier to debug, this PR calls the `aom_codec_err_to_string` public API to lookup the underlying error mesage.
```sh
$ heif-convert testimage.avif out.png
File contains 1 images
Could not decode image: 0: Invalid input: Unspecified: Bitstream not supported by this decoder
```
As originally reported at https://github.com/lovell/sharp/issues/2688
=> aom: expose decoder error messages to aid debugging

libheif/heif_encoder_aom.cc
Available from aom v3.1.0, the new "all intra" usage mode is now considered its best setting for still images.
From what I can tell, it uses a single pass and skips the keyframe logic (i.e. everything is intra-frame), resulting in significantly fewer memory allocations in addition to almost halving CPU time. The compression ratio is nearly identical, sometimes better, and the worst case I've found so far was 0.8% larger.
https://aomedia.googlesource.com/aom/+/refs/tags/v3.1.0
libavif has already adopted this as the default - see https://github.com/AOMediaCodec/libavif/pull/539
Homebrew currently provides aom v3.1.0 so the macOS CI job will test this.
=> aom: improve AVIF encoding performance by ~2x

gdk-pixbuf/pixbufloader-heif.c
GdkPixbuf objects are created with a reference count of 1. This fix decreases the reference count after use so it may actually be freed after use.
This fixes issue #509 - I tested on my machine and eog now really doesn't accumulate memory anymore.
=> Fix: decrease reference count on GdkPixbuf object so it can be freed

scripts/run-ci.sh
This better matches what the autoconf / automake environment uses.
=> CI: Use release build for cmake.

libheif/heif.cc, libheif/heif.h
Gives the C API access to the `HeifContext::set_max_decoding_threads`. For some reason it was missing, making it impossible to control threading, if enabled.
=> expose set_max_decoding_threads

.github/workflows/mingw.yml, scripts/install-ci-linux.sh, scripts/run-ci.sh
Needed a workaround for installing wine32 due to the GHA image being
broken (see https://github.com/actions/virtual-environments/issues/4589) (could also be worked around by using a docker image).
Might help #569
=> CI: use Ubuntu 20.04 for the mingw build to get a newer toolchain

.github/workflows/mingw.yml, libheif/heif.cc, libheif/heif_file.cc, libheif/heif_file.h, scripts/install-ci-linux.sh, scripts/run-ci.sh
This is platform specific, not compiler specific (i.e. it is also implemented by libstdc++ and libc++ on Win32 such as MinGW).
=> Enable wide chars for all Windows

README.md
Difference from pyheif:
1. Builds publicly on GitHub
2. Wheels for Linux, Alpine, macOS - x64, aarch64(arm64)
3. read_color_profile/read_metadata differs from pyheif(see 4)
4. Use it myself in public project(Nextcloud), heavily tested by admins, fast bug reports.
5. Contains some features that pyheif still hasn't.
=> Added pillow_heif for python bindings

libheif/heif_context.cc
Remove a reference to "XMP" in a comment in the add_generic_metadata()
method. This method is used to add all kinds of data, not just XMP data.
=> Remove reference to "XMP" in add_generic_metadata

libheif/heif_encoder_aom.cc
This allows callers to use different compression settings for the color
and alpha images.
Because of the backwards compatibility concerns I did not make lossless compression the default for the alpha image.
There are other AVIF encoders (e.g. libheif, Paint.NET) that do use lossless alpha compression as the default option.
=> AOM: Add separate quality options for the alpha image

libheif/heif_colorconversion.cc
If you look to `perf report`, this only function uses a lot of CPU while it is totally avoidable.
```
$ perf record python -m timeit -n3 -r10 \
-s "import pyheif; data = open('./full.norot.heic', 'rb').read()" \
"im = pyheif.read(data)"
```
master:
```
$ taskset 0x1 python -m timeit -n3 -r10 \
-s "import pyheif; data = open('./full.norot.heic', 'rb').read()" \
"im = pyheif.read(data)"
3 loops, best of 10: 479 msec per loop
```
native-rounding:
```
$ taskset 0x1 python -m timeit -n3 -r10 \
-s "import pyheif; data = open('./full.norot.heic', 'rb').read()" \
"im = pyheif.read(data)"
3 loops, best of 10: 386 msec per loop
```
I'm using `taskset 0x1` for more consistent benchmarks results.
=> Avoid lroundf using, overall 24% speedup for any images

libheif/heif_context.cc
This PR adds an extra check to prevent a possible stack overflow when the first value of `image_references` is the same as the `id` argument. I did not add an extra error message but if this is required then please let me know what the error message should be.
=> Added extra check to prevent recursion that could result in a stack overflow.

build-emscripten.sh
See https://github.com/emscripten-core/emscripten/issues/10784, and, possibly, https://github.com/strukturag/libde265/commit/f38489503ee55e6b937d26a4480b081e3c4245e4.
=> Update libde265 version and fix Emscripten error

tests/catch.hpp
...which currently is 2.13.9. This allows building with glibc >= 2.34,
which otherwise produces:
"catch.hpp:10376:58: error: call to non-'constexpr' function 'long int sysconf(int)'
10376 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
|                                                          ^~~~~~~~~~~"
Closes #539.
=> Update catch to the latest 2.x version

configure.ac
Adds a new optional `--disable-dav1d` autotools flag,
which defaults to "no".
Diff is best viewed with the "Hide whitespace" option.
=> build: allow to disable dav1d

libheif/heif_decoder_dav1d.cc
This is a copy-and-paste error (copied from heif_decoder_aom.cc).
=> Fix a comment error: aom_image_t => Dav1dPicture

libheif/heif_encoder_aom.cc, libheif/heif_init.cc
heif_encoder_aom.cc: In encoder_struct_aom::add_custom_option(), use the erase() method to remove an element from a std::vector.
heif_init.cc: In heif_unregister_encoder_plugin(), pre-increment the iterator, which does slightly less work than the post-increment operator (although compiler optimization is likely to take care of this for us). Also the get() method of std::unique_ptr can be avoided.
=> Some C++ cleanup

libheif/plugins/heif_encoder_aom.cc
Save the AV1 encoder name in a local variable to avoid a repeated call to aom_codec_iface_name(aom_codec_av1_cx()).
=> heif_encoder_aom: save encoder name in local var

libheif/plugins/heif_encoder_aom.cc
Set cfg.g_lag_in_frames, cfg.kf_mode, cfg.kf_max_dist to the default values of the AOM_USAGE_ALL_INTRA mode. This is useful when aomUsage is set to AOM_USAGE_GOOD_QUALITY or AOM_USAGE_REALTIME.
Also replace 0 with the symbolic constant AOM_USAGE_GOOD_QUALITY for readability.
=> heif_encoder_aom: use all intra mode cfg defaults

libheif/plugins/heif_encoder_aom.cc
Enable the libaom codec control AV1E_SET_SKIP_POSTPROC_FILTERING in the AOM_USAGE_ALL_INTRA mode for still-picture encoding.
This feature was recently added on the libaom main branch in https://aomedia-review.googlesource.com/c/aom/+/162681.
=> Enable libaom AV1E_SET_SKIP_POSTPROC_FILTERING

examples/heif_enc.cc
Helps making sure to keep the CI green :smile:
=> Fix compilation on Windows where gettimeofday does not exist.

libheif/plugins/heif_encoder_svt.cc
If rate_control_mode is set to 0 (the default), the rate control mode depends on the value of enable_adaptive_quantization. If enable_adaptive_quantization is 2 (the default), the rate control mode is constant rate factor (CRF). If enable_adaptive_quantization is 0, the rate control mode is constant QP. Since we don't set enable_adaptive_quantization, the rate control mode is CRF.
=> Change "constant QP" to "constant rate factor"

libheif/plugins/heif_encoder_aom.cc
AV1E_SET_ROW_MT is defined as an enum value rather than a macro. So #if defined(AV1E_SET_ROW_MT) is always false. Test the feature detection macro AOM_CTRL_AV1E_SET_ROW_MT instead.
Add a TODO comment for setting the codec controls AV1E_SET_TILE_ROWS and AV1E_SET_TILE_COLUMNS.
=> heif_encoder_aom: detect AV1E_SET_ROW_MT correctly

libheif/heif.cc
This takes the great work started in commit ffdac1e and extends it to ensure the cast from integer to enum value occurs as late as possible by storing integers in the `known_*` sets.
Without this change, UBSan currently reports the following:
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior plugins/heif_decoder_aom.cc:226:3
plugins/heif_decoder_aom.cc:226:3: runtime error: load of value 228, which is not a valid value for type 'aom_color_primaries_t' (aka 'aom_color_primaries')
0xab83f4 in aom_decode_image(void*, heif_image**)
0xa678db in heif::HeifContext::decode_image_planar(unsigned int, std::__1::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_decoding_options const*, bool) const
0xa66417 in heif::HeifContext::decode_image_user(unsigned int, …
```
=> Defer NCLX profile integer-to-enum-value conversion

gdk-pixbuf/CMakeLists.txt
Add L dirs of gdk-pixbuf-2.0 and its dependencies, so the shared libraries are found:
```
$ make
[..]
[ 46%] Built target heif
[ 65%] Built target heif-convert
[ 69%] Built target heif-info
[ 79%] Built target heif-enc
[ 83%] Built target heif-test
[ 95%] Built target heif-thumbnailer
[ 97%] Linking C shared module libpixbufloader-heif.so
ld: library not found for -lgdk_pixbuf-2.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gdk-pixbuf/libpixbufloader-heif.so] Error 1
make[1]: *** [gdk-pixbuf/CMakeFiles/pixbufloader-heif.dir/all] Error 2
make: *** [all] Error 2
```
**`pkg-config` output:**
```
$ pkg-config --libs-only-L gdk-pixbuf-2.0
-L/opt/homebrew/Cellar/gdk-pixbuf/2.42.10/lib -L/opt/homebrew/Cellar/glib/2.74.0/lib …
```
=> CMake: Fix build on macOS (with Homebrew packages)

gdk-pixbuf/CMakeLists.txt
@dloebl Used
```
cmake-format -i --line-width=130 --max-subgroups-hwrap 3 --max-pargs-hwrap 10 gdk-pixbuf/CMakeLists.txt
```
@farindk Please also include w/ https://github.com/strukturag/libheif/pull/647
=> cmake-format gdk-pixbuf folder

libheif/heif_context.cc
Encountered when asking svt-av1 to encode YUV444.
Similar code already exists for the equivalent HEVC code.
=> AV1: Stop encoding if plugin returns an error

gdk-pixbuf/CMakeLists.txt
Also, a DLL is not a "LIBRARY" type on Windows, let CMake handle this automatically.
=> Enable GdkPixbuf loader for mingw as well

libheif/plugins/heif_decoder_aom.cc, libheif/plugins/heif_decoder_dav1d.cc, libheif/plugins/heif_decoder_libde265.cc
This is a follow-up to #718 as the undefined behaviour was still being reported for some (fuzzer-found) inputs. I tracked this down to the use of a cast in the de265 decoder that is missing from the aom and dav1d decoders.
This change ensures all the decoders are consistent in their behaviour, using a `static_cast` for compile-time safety.
```
decoder enum value => uint16 => validate => libheif enum value
```
=> Ensure incoming NCLX enum values are cast to integer before validation

examples/CMakeLists.txt
Rewrite the CMakeLists.txt in a simpler way.
Test whether it works on all targets before merging.
=> simplifying examples/CMakeLists.txt

README.md
Source: https://github.com/Microsoft/vcpkg/#quick-start-windows
=> Update install instructions for vcpkg on Windows

libheif/CMakeLists.txt
=> cmake: Use CMAKE_DL_LIBS instead of dl to fix build on OpenBSD

libheif/heif_context.cc
Avoids a null-dereference in `decode_image_planar()`
The libvips fuzz tests caught this regression in commit https://github.com/strukturag/libheif/commit/e7515bb737423283aa2aad4d6ef74e93d1badea5
=> heif_context: test options before use

gdk-pixbuf/pixbufloader-heif.c
See e.g. the default JPEG, [PNG](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/aeda644f9690b346de77c8f7fae68f5661801833/gdk-pixbuf/io-png.c#L357-365) and TIFF loaders.
=> Add ICC extraction to gdk-pixbuf loader

libheif/plugins_windows.cc
Fix error:
```
libheif/plugins_windows.cc:65:7: error: unused variable 'nPlugins'
```
=> Fix unused variable nPlugins in libheif/plugins_windows.cc

libheif/box.cc
The current ItemLocationBox (iloc) parsing produces incorrect results when `version == 1`.
There are two problems, with the initial parsing of `index_size` which occurs in
```
if ((version == 1) || (version == 2)) {
unsigned int(4) index_size;
} else {
unsigned int(4) reserved;
}
```
and then in the extent parsing part:
```
if (((version == 1) || (version == 2)) && (index_size > 0)) {
```
(see ISO/IEC 14496-12:2015 Section 8.11.3.2).
The existing code does > 1, instead of >= 1 for both of those. That causes incorrect parsing of the `extent_offset` and `extent_length`.
The PR attached corrects the first case, and removes the second case (because its redundant - we already skip the case where `index_size` == 0). It would be equally valid to just make them both >= 1 though.
=> iloc: fix parsing with version == 1

libheif/plugins/heif_encoder_aom.cc
Call heif_image_get_bits_per_pixel_range(), not
heif_image_get_bits_per_pixel(), to get the bit depth of the image. The bug was introduced in commit 135f4ba0e2f13bedff4c81fc62bb49ae4bc61181.
Fix https://github.com/strukturag/libheif/issues/788.
=> heif_encoder_aom.cc: Get image bit depth correctly

libheif/heif.h
MPEG is working on ISO/IEC 23001-17 which defines the uncompressed codec. Add it to the list of compression formats to be implemented in the future.
=> Uncompressed Codec Placeholder

libheif/uncompressed_image.cc
Follow up from #808. 
I've kept the Y, Cb and Cr abbreviations, and switched the rest to lower case.
=> uncompressed: change cmpd component enum to match heif conventions

libheif/heif_hevc.cc
According to H.265 7.3.3
if( maxNumSubLayersMinus1 > 0 )
for( i = maxNumSubLayersMinus1; i < 8; i++ )
reserved_zero_2bits[ i ]
And x265 Entropy::codeProfileTier
if (maxTempSubLayers > 1)
{
WRITE_FLAG(0, "sub_layer_profile_present_flag[i]");
WRITE_FLAG(0, "sub_layer_level_present_flag[i]");
for (int i = maxTempSubLayers - 1; i < 8 ; i++)
WRITE_CODE(0, 2, "reserved_zero_2bits");
}
Should skip reserved bits to align to byte boundary in case of maxTempSubLayers > 1
=> Add reserved bits skip for NumSubLayers>1 in SPS

libheif/error.cc, libheif/heif.h, libheif/heif_file.cc, libheif/heif_file.h
Resolves  https://github.com/strukturag/libheif/issues/590.
Some derived images may contain cycles of image references in iref. Decoding such images leads to an out of memory error (which in turn may cause a DoS).
This PR adds an iref check, which detects cycles during image parse.
=> Add image reference cycle detection

libheif/heif_colorconversion.cc, tests/conversion.cc
If sharp yuv is requested but is not supported or fails, the whole encode fails rather than falling back to regular RGB->YUV conversion.
Reverts changes to Op_RGB24_32_to_YCbCr and adds
Op_RGB24_32_to_YCbCr_Sharp instead.
=> Refactor sharp yuv conversion to be a separate conversion step.

libheif/heif.cc, libheif/heif.h, libheif/region.h
This proposes two somewhat related changed to the region API.
The first is to represent polyline as distinct from polygon in the API. That avoids the need for checking if its closed, and more closely represents the way the standard describes it (and hopefully the way the user thinks about it). The underlying implementation is still shared - the API change just avoids exposing that implementation detail.
The second change is to switch both polygon and polyline to returning `heif_error`, rather than just not filling in any data in the points array. That should be checked, and also makes the API more consistent with the equivalent calls for point, rectangle and ellipse.
This should be seen as a proposal towards a final API, still subject to discussion.
=> regions: add polyline to regions API

libheif/color-conversion/colorconversion.cc, libheif/color-conversion/colorconversion.h, libheif/color-conversion/monochrome.cc, libheif/color-conversion/rgb2yuv.cc, libheif/color-conversion/yuv2rgb.cc, libheif/heif.h, tests/conversion.cc
Fix uncovered bugs/inconsistencies:
- make sure we don't downsample to 420 unless necessary
- fix sign in Op_YCbCr420_to_RRGGBBaa
- for monochrome, only accept heif_colorspace_monochrome+heif_chroma_monochrome (WARNING: behavior change, previously heif_colorspace_YCbCr+heif_chroma_monochrome was also valid)
=> Test all valid src/dst color state combinations in color test.

libheif/heif.cc
Note: we use `<cassert>` in other places that aren't guarded, so it should be safe outside the windows section here.
=> ci: attempt to fix windows build on appveyor

README.md
At least on my Debian Docker image the build failed with the previous parameter order. The official man page also says the options should be given first before the path.
`cmake [<options>] <path-to-source | path-to-existing-build>`
https://cmake.org/cmake/help/latest/manual/cmake.1.html
=> README: cmake parameter order

libheif/heif.cc
There is no POSIX matching write(), even w/ unistd.h present on e.g. MinGW, just an alias for Miscrosoft's CRT _write.
See also https://github.com/msys2/MINGW-packages/issues/17063
=> Handle _write() conversion warning on Windows

libheif/heif.cc, libheif/heif.h
The code to count the number of properties when out_list == nullptr was being skipped due to a null pointer check on that parameter.
Updated the header documentation for heif_item_get_properties_of_type and heif_item_get_transformation_properties to reflect this change.
=> Allow callers to get the number of properties

README.md
Adds resource cleanup to basic examples to resolve #651
Fixes some minor markdown linting errors.
=> doc: minor README.md cleanups

examples/heif_enc.cc
Using the heif-enc `--encoder ID` option (prior to this PR) produces:
```
$ ./heif-enc --encoder x265 something.png
Can't open x265
```
That is a bit confusing - its actually trying to open "x265" as an input file.
The option was missing an argument flag, which is added in this PR.
=> example: fix heif-enc encoder option

libheif/heif.cc, libheif/heif.h
Changed `heif_get_encoder_descriptors` to return the number of matching encoder descriptors when `out_encoders==nullptr`.
Updated the header documentation to reflect this change.
=> Allow callers to get the encoder descriptor count

libheif/hevc.cc
This fixes a build failure on SmartOS, see
https://us-central.manta.mnx.io/pkgsrc/public/reports/upstream-trunk/20230514.2249/libheif-1.16.1/build.log
```
/home/pbulk/build/graphics/libheif/work/libheif-1.16.1/libheif/hevc.cc: In function 'double read_depth_rep_info_element(BitReader&)':
/home/pbulk/build/graphics/libheif/work/libheif-1.16.1/libheif/hevc.cc:46:16: error: call of overloaded 'pow(int, int)' is ambiguous
46 |     value = pow(2, exponent - 31) * (1.0 + mantissa / pow(2, mantissa_len));
|             ~~~^~~~~~~~~~~~~~~~~~
```
=> Explicitly use std::pow.

tests/encode.cc
This is based on valgrind runs.
There are still some leaks, but they appear to be internal to x265.
=> tests: fix resource leaks in encode test

libheif/file.cc
The order in the file.h is:
void add_iref_reference(heif_item_id from, uint32_t type, const std::vector<heif_item_id>& to);
And in box.[cc,h]:
void add_reference(heif_item_id from_id, uint32_t type, const std::vector<heif_item_id>& to_ids)
=> file: fix argument order

examples/heif_convert.cc
Trivial fix for a typo I noted during work on #877, but isn't really related to that.
=> examples: fix typo in heif-convert help text

libheif/box.cc
Minor TODO fix.
Couldn't find a good formatting for the `has_compatible_brand()` part of the change. Please feel free to adjust.
=> ftyp: do not add compatible brand if already present

examples/heif-enc.1, examples/heif_convert.cc, examples/heif_enc.cc, examples/heif_info.cc, examples/heif_test.cc, examples/heif_thumbnailer.cc, scripts/run-ci.sh
This is a simplified (reduced scope) version of #856, just adding the version, and not attempting to do the configuration status.
Resolves #571
=> examples: add -v version command line options

libheif/heif.h
This is supported in some IDEs, as well as the HTML docs.
I'm doing this in small chunks to make it easier to review.
=> docs: add API documentation for heif_compression_format enum values

libheif/file.cc
https://github.com/strukturag/libheif/issues/888 identified that the semantics as implemented by #885 are likely incorrect. This PR disables writing of `1pic` pending further investigation.
=> temporarily disable 1pic brand

fuzzing/box_fuzzer.cc, fuzzing/color_conversion_fuzzer.cc, fuzzing/encoder_fuzzer.cc, fuzzing/file_fuzzer.cc, libheif/color-conversion/colorconversion.cc, libheif/color-conversion/colorconversion.h
By switching to `std::shared_ptr` we ensure that these smart pointers' lifetimes persist throughout the entire execution time of the program, eliminating the requirement of calling `heif_deinit()`.
This is especially useful in fuzzer environments where calling `heif_deinit()` is not always feasible.
Regressed since commit 8f9ac3d6db58d91ebb36f68244cdc534253b889b.
---
Context (in chronological order, none of them would appease OSS-Fuzz):
https://github.com/libvips/libvips/pull/3481
https://github.com/libvips/libvips/pull/3489
https://github.com/libvips/libvips/pull/3498
=> Fix a mem leak when `heif_deinit()` was not called

CMakeLists.txt, CMakePresets.json, tests/CMakeLists.txt, tests/encode.cc
[This is a somewhat speculative change - could see the case for backing some of it out]
Prior to this change, tests were only available if reduced symbol visibility was disabled.
That wasn't needed for the uncompressed codec tests. With a small change, it also isn't really needed for the encode tests.
=> tests: enable testing where practical

examples/heif_enc.cc, libheif/context.cc, libheif/context.h, libheif/file.cc, libheif/uncompressed_image.cc, libheif/uncompressed_image.h, tests/CMakeLists.txt, tests/uncompressed_encode.cc
Supports a limited range of inputs. 
Mono and simple RGB pixel interleave work OK.
YCbCr doesn't work correctly - encoded files look to have chroma problems when decoded with gpac and also with my viewer.
Additional work is needed for:
and probably other things...
@farindk would appreciate feedback on the approach if you have time.
=> uncompressed: initial work on encoder

libheif/color-conversion/rgb2yuv.cc, libheif/color-conversion/rgb2yuv_sharp.cc, libheif/color-conversion/yuv2rgb.cc, tests/conversion.cc
Some operators were not checking for matrix coefficients 0/8/11/14 even though they were not supported. It looks like the operation succeeds but get_RGB_to_YCbCr_coefficients and get_YCbCr_to_RGB_coefficients just return default values in this case (maybe this needs to be changed?)
There is only one operator that supports matrix_coefficients 8, and none of them support 11 or 14 currently.
=> Add more nclx conversion tests and fix related bugs.

libheif/plugins/CMakeLists.txt
As Darwin does not treat "loadable modules" (aka. bundles) as standalone libraries, neither identifiers nor version infos can be included.
This patch removes the version info for Darwin builds so plugins can be built correctly.
=> Fix build of libheif plugins on Darwin

examples/heif_info.cc
Recent GCC and Clang elevated this to an error.
=> Fix printf error

libheif/heif.h
Spotted building a user of libheif (imlib2) that uses `-Wstrict-prototypes`.
=> add a few (void) to please some compilers

libheif/uncompressed_image.cc
Originally, the Box_uncC::Component struct stored the (bit_depth - 1). Now that it stores the actual bit depth, remove the -1.
=> uncC: Store correct bit depth

examples/heif_info.cc, libheif/heif.cc, libheif/heif.h, libheif/uncompressed_image.cc, tests/region.cc
NB: Requires API version bump (at least when it comes to Windows)
Can of course be solved the other way (explicit casting to `unsigned long` where needed), if deemed safe.
This is because LLP64 on Windows vs LP64 everywhere else...
=> Use portable types to avoid cast warnings

examples/heif_info.cc, libheif/box.h, libheif/context.cc, libheif/context.h, libheif/file.cc, libheif/file.h, libheif/heif.cc, libheif/heif.h
The version 2 and 3 of the `infe` box has an `item_type` field that has special case meaning for values of `mime` and `uri `.
The box definition and parsing handles those cases, and the C API exposes the `content_type` that is present for the special case of `mime`.
This PR exposes the `item_uri_type` that is present for the special case of `uri `. This is used to indicate special metadata types for the GIMI profile.
The API and implementation for `heif_image_handle_get_metadata_item_uri_type()`  is essentially the same as `heif_image_handle_get_metadata_content_type()`.
This PR also makes use of that value (if present) in the heif_info example.
=> add support for URI metadata type

CMakeLists.txt, libheif.pc.in
One option of addressing https://github.com/strukturag/libheif/pull/943#issuecomment-1765953334
@pszemus Please test
=> CMake: detect C++ library for pkgconf file

libheif/CMakeLists.txt
Sets a darwin linker value that must be monotonic, which libtool automatically had been incrementing but cmake automatically sets to 1.0.0. Fixes  #992
=> cmake: Fix OS X compatibility_version based on libtool legacy

cmake/modules/FindAOM.cmake
aom could be installed in a non-standard prefix, preventing the aom encoder from being used.
<details>
<summary>Build log before</summary>
```
-- Looking for AOM_USAGE_GOOD_QUALITY
-- Looking for AOM_USAGE_GOOD_QUALITY - not found
```
```
Determining if the AOM_USAGE_GOOD_QUALITY exist passed with the following output:
Change Dir: /deps/heif/CMakeFiles/CMakeTmp
Run Build Command(s):/usr/bin/gmake cmTC_aa326/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_aa326.dir/build.make CMakeFiles/cmTC_aa326.dir/build
gmake[1]: Entering directory `/deps/heif/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_aa326.dir/CheckSymbolExists.c.o
/usr/bin/cc   -march=nehalem -Os -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -O3  -fPIE   -o …
```
=> CMake: correctly detect `AOM_USAGE_GOOD_QUALITY`

examples/heif_enc.cc
The option is `WITH_UNCOMPRESSED_CODEC` but we still had `ENABLE_UNCOMPRESSED_ENCODER`.
The original change was https://github.com/strukturag/libheif/commit/9895fdf37558c2efdbaeeb5e29504be03e88e8f8#diff-30575ea3ee10e63b2610466a76c0391eb3a6a3b1984b80ddc668421fa095929c
I think this part may have been accidentally reverted during the JPEG 2000 merge.
=> examples: correct configuration check for uncompressed codec in heif-enc

libheif/color-conversion/colorconversion.cc, libheif/nclx.cc
Since commit 062b5284216748925cdbf67f9eb8a12bbda503e1, libheif saves images with the default NCLX profile `6,6,6` (Rec. 601 aka NTSC) which is pretty far from sRGB and leads to incorrect colors in most viewers. Additionally, the `colr` HEIF box wasn't updated to reflect this.
Commit 673fb03227790cb5184c9c9aaa5c40775cb3afbf resolves the latter issue by guaranteeing the update of `target_nclx_profile` following the color conversion, thereby ensuring the propagation of any defaults specified in `ColorConversionPipeline::convert_image()`.
Commit 3bc75720f9eb686e2a674a710961422b9920d2e3 resolves the former issue by ensuring NCLX profiles defaults to `1,13,1`  (Rec. 709 with IEC 61966-2-1 transfer function).
Context: https://github.com/libvips/libvips/pull/3731
Thanks to @DarthSim for …
=> nclx: use default values that match sRGB

libheif/box.cc, libheif/box.h, libheif/heif_properties.cc, libheif/heif_properties.h
Feedback is always appreciated.
=> Heif Properties: Timestamp boxes

libheif/plugins/encoder_kvazaar.cc
Hey there 👋
Currently, `kvazaar_query_input_colorspace2` preserves input `chroma`, and encoding of an RGBA input fails because of this. This PR makes `kvazaar_query_input_colorspace2` rewrite `chroma` if it is incompatible with `heif_colorspace_YCbCr`.
=> kvaazar: set chroma in kvazaar_query_input_colorspace2

libheif/uncompressed_image.cc
=> uncompressed: fix component type validity check

gnome/CMakeLists.txt
Regression was introduced in 060b55c93ef2338998bf8bcc542421d9f5fd99fd.
Noticed this while working on the packaging of 1.17.4.
=> Fix installing Gnome files if examples are build.

README.md
Commit 4a817ab changed the name of the plugin, but README was not updated accordingly.
=> doc: fix ffmpeg codec name in README.md

libheif/uncompressed_image.cc
=> uncompressed: protect against broken uncC box component references

libheif/uncompressed_image.cc
fix #1065: Null pointer dereference in UncompressedImageCodec::decode_uncompressed_image
=> fix null pointer dereference in libheif/uncompressed_image.cc:758

libheif/plugins/encoder_svt.cc
Resolves #956
See #956 for the MSVC and clang warning (that becomes an error)
=> svt: fix c99 extension warning

libheif/CMakeLists.txt, libheif/avc.cc, libheif/avc.h, libheif/box.cc, tests/CMakeLists.txt, tests/avc_box.cc
There doesn't appear to be much use of AVC - the only test file I'm aware of is https://github.com/nokiatech/heif_conformance/blob/master/conformance_files/multilayer004.heic
However I'd eventually like to support it, and this is an initial step.
=> avc: implement avcC box parsing

examples/encoder_jpeg.cc
Relates #1042.
https://github.com/strukturag/libheif/commit/26ec3953d46bb5756b97955661565bcbc6647abf resolved #1042 with protection against EXIF overflow in the JPEG encoder.
However the report at #1042 was against the PNG encoder.  That is addressed at #1052. The review for that identified that its possible to get an overflow in the `size += 4`, and it looks like that is possible in the JPEG version too.
This PR incorporates the same fix as suggested for #1052.
=> exif: protect against EXIF data overflow

extra/getopt_long.c, libheif/context.cc, libheif/plugins/encoder_svt.cc
Made the implementation of getopt_internal match the declaration
Fix warning about the unsafe use of int as bool
Remove unnecessary cast (SvtAv1FixedBuf) causing compiler error
=> Fix build warnings and errors in Visual Studio 2022

libheif/box.cc, tests/CMakeLists.txt, tests/idat.cc
This one showed up in box fuzzing.
I wasn't sure about creating a new unit test - can drop that part if you would prefer.
=> idat: protect against trying to output negative size

examples/encoder_jpeg.cc
fix #1073: memory leaks in function JpegEncoder::Encode
=> fix memory leaks in function JpegEncoder::Encode

libheif/color-conversion/hdr_sdr.cc, libheif/pixelimage.cc, tests/conversion.cc
This is a partial fix for color conversion from planar RGB with bit depth less than 8 bit into 8 bit. It extends an existing operation (`Op_to_sdr_planes`) to handle this case.
This is enough to get my uncompressed codec rework with `heif-convert` to generate JPEG. However it is not sufficient for PNG.
=> colorconversion: add support for promoting < 8 bit planar to 8 bit planar

appveyor.yml
Update the AppVeyor CI configuration to the Visual Studio 2022 image. This [updates](https://www.appveyor.com/docs/windows-images-software/) Visual Studio from 16.11.24 to 17.5.0.
AppVeyor builds can be viewed at: https://ci.appveyor.com/project/strukturag/libheif
=> AppVeyor CI: Update to Visual Studio 2022 image

libheif/plugins/encoder_kvazaar.cc
The background:
I am trying to build libheif to wasm with kvazaar.
The building is successful but it run with error from kvazaar:
```
--threads=auto value set to 4.
pthread_create failed!
Could not initialize threadqueue.
```
It seems that kvazaar doesn't provide a build option for disable threads, the only way is settings `config->threads` to `0` at runtime.
=> Set kvazaar config threads to 0 if ENABLE_MULTITHREADING_SUPPORT is false

CMakePresets.json, README.md
In this PR, there is a new `default` preset in CMakePresets.json reflecting the CMakeLists.txt default plugin options and a `base` preset.
The change should not have any consequences in the builds except the ones building using the default preset (`cmake --preset=default ..`).
=> Cleaner presets for CMake

libheif/file.cc, libheif/file.h
This is a tentative PR to resolve a clang-tidy recommendation - "The parameter 'property' is copied for each invocation but only used as a const reference; consider making it a const reference"
In some ways it feels like a micro-optimisation, but an easy change and also useful to keep the IDE "noise" down so that real issues are easier to see.
=> add property by reference

libheif/plugins/encoder_aom.cc, libheif/plugins/encoder_openjpeg.cc, libheif/plugins/encoder_rav1e.cc, libheif/plugins/encoder_svt.cc, libheif/plugins/encoder_x265.cc
In the encoder plugins, we have code that looks like:
https://github.com/strukturag/libheif/blob/master/libheif/plugins/encoder_aom.cc#L648-L678
The problem is that if we return `heif_error_unsupported_parameter` even if it is valid.
That doesn't show up in `heif-enc` example, because we ignore the return value. However it doesn't look reasonable.
There is another problem in some of the codecs, where we assume the only string parameter is `chroma`. 
This PR addresses both issues across the codecs that have the problem (pretty much anything that supports a string parameter, given the way the plugins have developed).
Note that there are likely similar problems in other methods, but I wanted to keep this PR simple.
=> plugins: fix return value for X_get_parameter_string()

examples/heif_enc.cc
Resolves #1102
Also fixes some other potential leak points, and a missing `nclx` free
=> heif-enc: fix encoder leak when using --params

tests/encode_jpeg2000.cc
This was in #1071, but appears to have been dropped during the split of that PR.
=> jpeg2000: add missing test code for JPEG 2000 encoding

libheif/plugins/encoder_openjpeg.cc, tests/encode_jpeg2000.cc
These show when running the unit tests or heif-enc under valgrind.
=> openjpeg: fix memory leaks

examples/decoder_png.cc
This shows up with heif-enc (e.g. with --avif) under valgrind
=> examples: fix leak in PNG decoder

.github/workflows/osx.yml
See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
=> CI: add macOS arm64 job

libheif/plugins/encoder_kvazaar.cc
This fixes the following memory leaks:
- the `data` chunks are not freed in all cases after being appended to the encoder output
- `append_chunk_data` throwing an exception (std::bad_alloc) would not free any of the kvazaar-structures
At least the successful encoding case should be leak-free now: The address sanitizer does not report any leaks.
I did not test the exceptional cases - using unique_ptr this should be no different than the successful case.
=> encoder_kvazaar.cc: Fix some memory leaks

libheif/box.cc
The construction method of 2 is currently being interpreted as a character (not a number), and doesn't appear.
Also the suberror shouldn't indicate a missing `idat`.
=> iloc: fix error message

libheif/box.cc, libheif/box.h, libheif/file.cc
Reusing identical properties will help clean up the ipco box. It becomes cumbersome when there are many images like this:
=> Reuse matching ispe box if one exists.

third-party/aom.cmd, third-party/dav1d.cmd
Similar to the message added to third-party/svt.cmd in commit 1a1b4d4d.
=> Echo a message on setting PKG_CONFIG_PATH

libheif/heif_items.h
This is for the develop-v1.18.0 branch, not master.
=> Add comments for heif_context_get_item_references()

examples/heif_convert.cc, libheif/heif.cc, libheif/heif.h
Keeps the existing `heif_check_filetype` behaviour since that is public API. Adds a new function to check both the major version and the compatible_brands list. Switches the heif-convert example to use that new function.
I have put an arbitrary 512 byte limit on how long we expect the `ftyp` box could be. That seems reasonable, but could be higher or lower.
The goal of this is to support files that are both video and images (sharing data), where the major_brand is something like `mp41` but `heic` is listed in the `compatible_brands[]`.
=> libheif: check compatible brands in the ftyp box

libheif/plugins/encoder_jpeg.cc
Fix the following libjpeg build failure raised since version 1.17.0 and https://github.com/strukturag/libheif/commit/ebd13a20b8b7f1964939642b08b662ef7e483f39 because third argument of `jpeg_mem_dest` is defined as `size_t*` on libjpeg instead of `unsigned long*` on jpeg-turbo:
```
/home/buildroot/autobuild/instance-3/output-1/build/libheif-1.17.5/libheif/plugins/encoder_jpeg.cc: In function 'heif_error jpeg_encode_image(void*, const heif_image*, heif_image_input_class)': /home/buildroot/autobuild/instance-3/output-1/build/libheif-1.17.5/libheif/plugins/encoder_jpeg.cc:366:37: error: invalid conversion from 'long unsigned int*' to 'size_t*' {aka 'unsigned int*'} [-fpermissive]
366 |   jpeg_mem_dest(&cinfo, &outbuffer, &outlength);
|                                     ^~~~~~~~~~
| …
```
=> libheif/plugins/encoder_jpeg.cc: fix libjpeg build

libheif/context.cc, libheif/context.h
Initial work (for discussion / review) on support for shared alpha images.
Relates #1147 
I've shown some commented out code that returns an error if the alpha requires scaling (which is valid in HEIF). Until we support that, the options are silently ignoring the alpha plane, or not supporting the image at all.
We do have some scaling code, but my attempt to apply it failed - its designed for an image, not an image plane, and the refactoring got away.
Fixes / suggestions appreciated.
=> libheif: support for shared auxl alpha images

libheif/plugins/decoder_ffmpeg.cc
* memory leak fix
* heap buffer overflow fix
These issues were caught by ASAN
=> Fix some bugs in ffmpeg decoder plugin

libheif/box.cc, libheif/heif.cc, libheif/heif_properties.cc
When building develop-v1.18.0 branch on Ubuntu 24.04 (gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0), I hit this:
```
[  2%] Building CXX object libheif/CMakeFiles/heif.dir/box.cc.o
/home/bradh/coding/libheif/libheif/box.cc:3451:86: error: return type ‘struct std::array<double, 9>’ is incomplete
3451 | std::array<double,9> mul(const std::array<double,9>& a, const std::array<double,9>& b)
|                                                                                      ^
/home/bradh/coding/libheif/libheif/box.cc: In function ‘void mul(const std::array<double, 9>&, const std::array<double, 9>&)’:
/home/bradh/coding/libheif/libheif/box.cc:3453:24: error: aggregate ‘std::array<double, 9> m’ has incomplete type and cannot be defined
3453 |   std::array<double,9> m;
|                        ^ …
```
=> libheif: add <array> includes

libheif/context.cc, libheif/context.h, libheif/heif.cc, libheif/heif.h
LIBHEIF_API
struct heif_error heif_context_encode_grid()
Resolves #1176, resolves #648
=> Encode Grid

third-party/svt.cmd
Remove the no-dec build option because the decoder portion of SVT-AV1 was removed in v2.1.1.
=> Update to SVT-AV1 v2.1.1

libheif/plugins/decoder_ffmpeg.cc
In this patch, support for mono, 422, 444 are added.
In terms of implementation:
* The check whether a pixel format is supported is moved into ffmpeg_get_chroma_format
* chroma_width and chroma_height needs to be computed separately for 422, 444 as they are different from 420
For testing: I created mono, YUV422, YUV422 samples with heif-enc and ran with ffmpeg plugin with ASAN. I validated that chroma_height and chroma_width are correctly set as they can cause heap-read-out-of-bound if not set correctly.
=> [ffmpeg plugin] Add more chroma subsampling support

libheif/bitstream.cc, libheif/bitstream.h, libheif/box.cc, libheif/box.h, libheif/heif_properties.cc, libheif/heif_properties.h
This branch was used to create the following [sample file](https://github.com/dukesook/test-files/blob/master/timestamps/timestamps.heif).
```C++
aligned(8) class TAIClockInfoBox extends FullBox('taic', 0, 0) {
unsigned int(64) time_uncertainty;
unsigned int(32) clock_resolution;
signed int(32) clock_drift_rate;
unsigned int(2) clock_type;
unsigned int(6) reserved = 0;
}
```
```C++
aligned(8) class TAITimestampBox extends ItemFullProperty('itai', 0, 0) {
TAITimestampPacket timestamp_packet;
}
```
```C++
aligned(8) class TAITimestampPacket {
unsigned int(64) TAI_timestamp;
unsigned int(1) synchronization_state;
unsigned int(1) timestamp_generation_failure;
unsigned int(1) timestamp_is_modified;
unsigned int(5) reserved = 0;
}
```
=> DAM1 update for timestamps

libheif/api/libheif/heif_emscripten.h
Currently if you want to check the filetype of some buffer in javascript you need to do something like:
```js
const dummy_buffer = new Uint8Array([]) // pretend this has the image data
const ptr = Module._malloc(12);
if (!ptr) {
//...
}
Module.HEAPU8.set(dummy_buffer.subarray(0, 12), ptr);
const res = Module._heif_check_filetype(ptr, 12);
Module._free(ptr);
if (res === 1) {
// valid
}
// handle other cases
```
This is not only alot of manual memory management on the javascript side but also requires defining a copy of the  `heif_filetype_result` enum on the javascript side to avoid using hardcoded numbers since the enum is not exported by the emscripten bindings.
With new bindings it would be simplified to:
```js
const res = Module.heif_js_check_filetype(dummy_buffer)
if (res.value === …
```
=> Add convenience bindings for javascript to check filetype and to get primary image handle 

libheif/plugins/encoder_aom.cc
=> aom: Use all available CPUs for encoding by default.

CMakeLists.txt, README.md, libheif/codecs/vvc.cc, libheif/plugin_registry.cc, libheif/plugins/CMakeLists.txt, libheif/plugins/decoder_vvdec.cc, libheif/plugins/encoder_uvg266.cc, libheif/plugins/encoder_vvenc.cc, libheif/plugins/encoder_vvenc.h
First working version.
Currently only supports 8 bit encoding. Higher bit depths will also require changes in the vvdec plugin.
=> add vvenc VVC encoding plugin

libheif/codecs/uncompressed_box.cc, tests/uncompressed_box.cc
Resolves #1206 
Includes unit test.
This does not make the limit configurable, but that could be added.
Should we have the same limit for the number of image grid rows and columns?  That already has a short-form and long-form option, but no limits on the long form case:
https://github.com/strukturag/libheif/blob/7a8c58e4be8b3eb77d82330a407a7f5e6da15a44/libheif/context.cc#L189-L212
=> uncompressed: add sanity limit check on number of tile rows and cols

libheif/context.cc
The libvips' fuzz tests found a possible integer overflow here:
https://github.com/strukturag/libheif/blob/7c9729ea8d0f319ab423f8e4e6de121fd78596d0/libheif/context.cc#L1938
```
/src/libheif/libheif/context.cc:1938:8: runtime error: signed integer overflow: 1344282656 + 1344282656 cannot be represented in type 'int'
0 0x5b6b1f26031b in HeifContext::decode_full_grid_image(unsigned int, std::__1::shared_ptr<HeifPixelImage>&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, heif_decoding_options const&) const libheif/libheif/context.cc:1938
1 0x5b6b1f258489 in HeifContext::decode_image_planar(unsigned int, std::__1::shared_ptr<HeifPixelImage>&, heif_colorspace, heif_decoding_options const&, bool) const libheif/libheif/context.cc:1512
2 0x5b6b1f256d36 in …
```
=> context: add sanity-check to tile dimensions/resolution

libheif/compression.h
This is a follow-up to the recent work on compression / decompression, adding some internal documentation on those.
It isn't going to show up in the Doxygen since its not public API. Depending on editor, it may show up as a hint. For example, in VS Code, it appears on hover:
=> compression: add (internal) api documentation for compression

examples/heif_info.cc
Minor item I noted while working on the uncompressed codec support for these data types.
=> examples: display non-visual colorspace entry in heif-info

libheif/codecs/uncompressed_box.cc
This ensures the newline appears. Otherwise the first component gets pasted on the end of the line.
=> uncompressed: fix box dump when profile is 0

examples/heif_dec.cc
In Windows, file paths may contain colons, so replacing colons in file paths is not appropriate. Therefore, I propose modifying the code to only replace colons in auxType.
Proposed Changes
Modify the code to ensure that only colons in auxType are replaced, leaving file paths with colons intact.
=> fix heif_dec no-colons option for windows

.github/workflows/coverity.yml
- Run "cmake" before building.
- Enable more codecs.
- Build on PRs (but don't upload to Coverity).
=> Fix coverity build.

scripts/install-ci-linux.sh, third-party/rav1e.cmd
rav1 was not built due to compiler error for some time now (see https://github.com/strukturag/libheif/actions/runs/9890048988/job/27319594102#step:3:2004 for an example CI run). As this didn't fail the CI job, the problem went unnoticed and we lost some compile coverage.
This PR changes this, so that if any of the third-party `.cmd` files contains a command that fails, the whole script will fail and with that, the CI job.
=> CI: Fail if third-party build fails.

libheif/api/libheif/heif_properties.cc
I saw link time failures with this function.
Looks like the rename only happened in the header.
=> rename property raw data implementation to match header

libheif/api/libheif/heif_properties.cc, libheif/api/libheif/heif_properties.h, tests/CMakeLists.txt, tests/extended_type.cc
This is an alternative approach to solving #1244, adding a function to get the UUID (`extended_type` field).
Also includes documentation, a unit test, and some refactoring of shared code.
=> libheif: add API to get UUID for user extension boxes

libheif/codecs/uncompressed_image.cc, libheif/codecs/uncompressed_image.h, libheif/context.cc, libheif/file.cc
This fixes incorrect bit depth and format display for the uncompressed codec with data other than YCbCr.
This also shows up in the API, and hits some no-longer-valid assumptions in GDAL for formats like monochrome.
=> uncompressed: correctly set chroma and format

examples/CMakeLists.txt, examples/encoder_tiff.cc, examples/encoder_tiff.h, examples/heif_dec.cc
Inspired by the TIFF decoder (and a cold wet morning), I've implemented a very basic TIFF encoder.
There are a lot more things we can do with TIFF over PNG/JPEG/Y4M. For example, it could do multiple images per file (instead of splitting them), different compression types and levels, different chroma or interleave formats etc. It could also do the various sample types (e.g. signed, float, etc), which is part of the reason for wanting it. None of that is done yet, partly because it will complicate the Encoder API and command line options. 
I wonder if we should have only limited TIFF support for `heif-dec`, or whether to extend the `Encoder` API. Related, we could have HEIF as an output format (e.g. so you can pull in HEIC and output AVIF, or JPEG-2000, or uncompressed, or some other …
=> examples: initial TIFF encoder support

libheif/plugins/decoder_openjpeg.cc
Fixes calling convention mismatch in unique_ptr declaration by adding OPJ_CALLCONV to the deleter function pointer type.
This fixes the build for 32bit Windows, where the default calling convention doesn't match OPJ_CALLCONV, which is used by all three functions.
This issue was introduced in 4851124559d2cbccc50
(and later adjusted in 242331c3e74a5ba7c)
Fixes #1262
=> decoder_openjpeg: Add OPJ_CALLCONV to unique_ptr deleter

libheif/codecs/uncompressed_image.cc
This is the RGB with alpha part of #1267.
I also noted that the version 1 case wasn't displaying the bit depth correctly, which is resolved by this.
There is still an issue where heif-info shows "alpha channel: no", because its looking for an aux image, not at the actual image channels.
@farindk Can you verify that it works for your test cases?
=> uncompressed: fix decoding of images with rgba profile

libheif/codecs/uncompressed_image.cc
This is the YCbCr part of #1267.
I'm actually surprised it encoded at all (rather than segfaulting), however now valgrind clean.
@farindk Can you confirm this works for your test cases?
=> uncompressed: fix encoding of YCbCr with subsampling

libheif/codecs/uncompressed_box.cc, libheif/codecs/uncompressed_box.h, libheif/compression_zlib.cc
This avoids the potential for undefined behaviour, as well as making the implementation a bit simpler.
=> uncompressed: simplify compressed units handling

.github/workflows/coverity.yml
This fails for most users, and is confusing for occasional contributors.
=> ci: remove coverity from PR

libheif/plugins/encoder_aom.cc
Discovered via fuzz testing.
Resolves: https://github.com/libvips/libvips/issues/4109.
=> encoder_aom.cc: fix memory leaks

libheif/plugins/encoder_x265.cc
libx265 4.0 has changed the signature of `x265_api::encoder_encode` and `x265_encoder_encode` functions to accept a pointer to an array of pointers to output pictures. That pointer is now required to be non-null, otherwise the encode call crashes.
Upstream bug report: https://bitbucket.org/multicoreware/x265_git/issues/952/crash-in-libheif-tests
=> Update for compatibility with libx265 4.0

tests/tiffdecode.cc
This addresses an appveyor CI failure where the `heif_image_has_channel()` call returns `int`, not `bool`.
=> tests: match tiffdecode test calls to signature

libheif/security_limits.cc
Commit https://github.com/strukturag/libheif/commit/2374ade0a24f107d5de8fb6bd5f9ceef04b6c510 allows security limits to be set per context but also removed/altered a couple of the original limits. Removing the `max_iloc_items` limit opens libheif to a denial of service attack. This PR restores the previous defaults.
=> Security: restore previous default limits prior to commit 2374ade

libheif/plugins/encoder_aom.cc
Setting this option allows libaom to determine the optimum tile count for the given output dimensions and available threads.
This typically reduces encoding (wall clock) time and/or peak RAM consumption at the cost of slightly increased file sizes. I see a ~30-50% speed up on many-core systems.
```
$ /usr/bin/time -v heif-enc in.jpg -o out.avif
User time (seconds): 1.71
System time (seconds): 0.03
Percent of CPU this job got: 258%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.67
Maximum resident set size (kbytes): 50432
```
```
$ /usr/bin/time -v heif-enc -p auto-tiles=true in.jpg -o out.tiled.avif
User time (seconds): 2.23
System time (seconds): 0.04
Percent of CPU this job got: 588%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.38
Maximum resident set size (kbytes): 52864
``` …
=> aom encoder: expose auto-tiles boolean option (since v3.10.0)

libheif/plugins/encoder_x265.cc
Tested:
```
$ build/examples/heif-enc lena.490x490.png -p x265:colorprim=12 -p x265:foo=bar -o /tmp/foo.heic
Could not encode HEIF/AVIF file: Usage error: Unsupported parameter: Unsupported internal encoder parameter: x265:foo
```
=> heif-enc: exit with invalid x265 internal parameters

libheif/api/libheif/heif.h
VVC is now used.
No code changes in this.
=> doc: update API documentation

libheif/api/libheif/heif.cc, tests/uncompressed_decode.cc
This shows that we are not advertising decoder support for uncompressed.
The base reason is that it checks for the compression type in the list of plugins, and there is no plugin for uncompressed decode. There is one for uncompressed encode.
This doesn't show up in the heif-dec example code, because it has a hard-coded response depending on compile time option for uncompressed.
I can see two ways forward:
- add a dummy decoder plugin
- add a special case (depending on compile time option for uncompressed) to `heif_have_decoder_for_format()`.
@farindk your preference?
=> test case for uncompressed decoder advertisement

libheif/api/libheif/heif_properties.h
This showed up as errors during a mac "homebrew" build for GDAL.
See https://github.com/bradh/gdal/actions/runs/11888292592/job/33122567658#step:9:1170
I think the real problem with that is the size thing, but this is mentioned.
=> properties: update doxygen comments

examples/heif_enc.cc
fixed missing string conversion
=> examples/heif_enc.cc: fixed missing string conversion

libheif/plugins/encoder_aom.cc
The "intra block copy" feature of the AV1 codec can lead to an order of magnitude increase in encoding time when certain conditions/dimensions are met.
This feature, which is switched on by default in libaom but not always triggered, searches for similar areas within the same frame, e.g. repeating text, but at a high CPU cost. My understanding is that it can also prevent the use of (decoding?) loop filters, so useful features like deblocking and deringing are skipped.
There is more context and discussion, including comments from libaom maintainers, at https://github.com/libvips/libvips/issues/2983
/cc @kleisauke who suggested the original patch
=> AOM encoder: Expose control over Intra Block Copy (intrabc)

libheif/plugins/encoder_aom.cc
The AOM_CTRL_AV1E_SET_ENABLE_INTRABC macro has been defined since the v1.0.0-errata1-avif tag. We can assume AOM_CTRL_AV1E_SET_ENABLE_INTRABC is defined and remove all the AOM_CTRL_AV1E_SET_ENABLE_INTRABC checks.
=> Remove AOM_CTRL_AV1E_SET_ENABLE_INTRABC checks

libheif/plugins/decoder_openh264.cc
This patch fixes an out of range assert with a debug build on Windows:
```c++
_NODISCARD _CONSTEXPR20 const _Ty& operator[](const size_type _Pos) const noexcept /* strengthened */ {
auto& _My_data = _Mypair._Myval2;
#if _CONTAINER_DEBUG_LEVEL > 0
_STL_VERIFY(
_Pos < static_cast<size_type>(_My_data._Mylast - _My_data._Myfirst), "vector subscript out of range");
#endif // _CONTAINER_DEBUG_LEVEL > 0
return _My_data._Myfirst[_Pos];
}
```
This happens when `idx + size == indata.size()` and can be avoided by getting the address of the last element and then adding `1` to the pointer.
=> Patch to avoid out of bounds assert with a debug build on Windows.

libheif.pc.in
This is just one (small) step in addressing e.g. #513 and #902 for _clients_ of the static library (for which the correct OOTB _build_ of on Windows still needs to be handled).
This is not gated by WIN32 anywhere (i.e. placeholder to be conditionally substituted by CMake), but it doesn't affect other platforms, so might as well hard code it...
=> Add static flag to libheif.pc

libheif/box.cc
Commit https://github.com/strukturag/libheif/commit/41ccc4e82dfd7e0e2f40b27a959ade9ead8304a8 added support for limiting `max_size_entity_group` as part of libheif v0.19.0. This PR adds the necessary return to enforce that limit.
=> Security: ensure max_size_entity_group limit is enforced

.gitignore, CMakeLists.txt, libheif/CMakeLists.txt
Greetings,
Similar to the [PR in libde265](https://github.com/strukturag/libde265/pull/466), I added the essential properties to the `heif` target to enable cross-compilation for iOS derived platforms.
Since libheif **depends on** [libde265](https://github.com/strukturag/libde265), the framework artifacts of libde265 must exist on local machine in order to cross compile libheif for a desired Apple platform. 
The following commands could be used to generate the frameworks for an iOS target:
```bash
cmake -S. -B build -DBUILD_FRAMEWORK=TRUE -DCMAKE_SYSTEM_NAME=iOS -DWITH_EXAMPLES=OFF
sudo cmake --build build --target install --config Release
```
Note that `WITH_EXAMPLES=OFF` has to be off since I didn't find it necessary to modify the properties of _Examples_.
=> Add support for Apple framework builds

libheif/plugins/encoder_jpeg.cc
=> encoder_jpeg.cc: Fix for libjpeg versions < 9d

libheif/plugins/encoder_aom.cc
Prints a warning if setting the custom AOM encoder option fails.
I assume we don't want to return an error as described in https://github.com/pszemus/libheif/blob/master/examples/heif_enc.cc#L165 for x265 encoder, but since we have an actual error message here, maybe we want the whole operation (AOM encoder setup) to fail?
=> aom: print warning on `aom_codec_set_option` failure

libheif/plugins/encoder_openjph.cc
Resolves #1434 
I've built this locally, and on a Debian 12.8 VM.
Actually running it on such an old version of OpenJPH could be buggy, but at least it should compile.
=> openjph: fix compilation with ancient library versions

libheif/plugins/encoder_aom.cc
The aom `tune` value of `iq` is an acronym of "Image Quality" and is based on the more up-to-date SSIM version 2. This is made available from libaom version 3.12.0 onwards hence the `#if defined` guard.
The existing default `tune` value of `ssim` remains to ensure backwards compatibility.
=> aom encoder: allow tune parameter value of "iq"

examples/heif_view.cc
SDL_GetTicks64 was introduced in SDL 2.0.18 but Ubuntu 20.04 still ships 2.0.10
=> Support versions of libsdl2-dev before 2.0.18

libheif/sequences/seq_boxes.cc
The change in this PR also ensures 64-bits of precision are used when calculating the required memory allocation, preventing a possible 32-bit overflow.
This was discovered by the libvips' fuzz tests. If required I can provide an 86 byte (!) AVIF image that results in a memory allocation in excess of the default 4GB limit.
=> seq_boxes: saio samples are always stored as uint64

libheif/sequences/seq_boxes.cc
Ensures the same fail-fast approach as used with the other boxes parsed by this file.
=> seq_boxes: check for sbgp read errors within loop

post.js
The call to heif_image_handle_is_primary_image in HeifImage.prototype.is_primary was missing "Module.", so the function isn't able to be called successfully.
=> Fix call to heif_image_handle_is_primary_image

libheif/color-conversion/yuv2rgb.cc
I've been doing to profiling of libvips with various formats and the (relatively common) subsampled YUV to RGB colour conversion logic is a hot code path when calling `heif_decode_image` with `heif_colorspace_RGB`.
At first glance this PR appears to make things look slightly more complex, but in my testing the following changes allow the compiler (I'm using gcc) to optimise and auto-vectorise the inner loop more easily:
- Move row pointer calculations out of the inner loop
- Only update offsets every other pixel due to use of sub-sampling
I tested with `-DCMAKE_BUILD_TYPE=Release`, which I think is equivalent to `-O3`, using a 12 megapixel image from https://heic.digital/samples/
Before (best time over 10 runs):
```
$ time vips copy greyhounds-looking-for-a-table.heic out.v
real	0m0.264s …
```
=> yuv2rgb: improve performance of 4:2:0 YUV to RGB conversion by ~15%

libheif/api/libheif/heif_cxx.h
Clang++ on macOS will display the following warning message:
Clang++ version: Apple clang version 17.0.0 (clang-1700.0.13.5)
libheif version: 1.20.1 (homebrew)
We can eliminate this warning by explicitly specifying the initialization of all struct members.
=> Fix clang++ missing field 'request_range' initializer warnings

libheif/api/libheif/heif_emscripten.h, post.js
Allow javascript code to call heif_image_handle_has_alpha_channel and heif_image_handle_is_premultiplied_alpha.
=> Expose alpha related functions to javascript

libheif/plugins/CMakeLists.txt
While packaging libheif 1.20.1 for Debian, I noticed this error while running the tests:
```
7: dlopen: /build/libheif-1.20.1/obj-x86_64-linux-gnu/libheif/plugins/libheif-svtenc.so: undefined symbol: _ZN5Error2OkE
```
Similar to #1541, the plugin needs linking to `error.cc`.
Maybe there should be an internal common static library that is linked by all plugins, so you have to specify these dependencies (together with `common_utils.{cc,h}`) only once.
=> Fix undefined symbol "Error::Ok" in svtenc plugin.

CMakeLists.txt, libheif/bitstream.cc
This fixes an issue when building on older OSX with clang (reported as `Apple LLVM version 10.0.1 (clang-1001.0.46.1)` but doesn't provide the `bit` header.
=> Move check for "bit" header to cmake.

CMakeLists.txt, build-emscripten.sh, libheif/api/libheif/heif_emscripten.h, libheif/plugin_registry.cc, libheif/plugins/CMakeLists.txt, libheif/plugins/decoder_webcodecs.cc, libheif/plugins/decoder_webcodecs.h, libheif/plugins/nalu_utils.h, post.js
Decodes images using the VideoDecoder API when run from webassembly in a browser.
The plugin calls inlined Javascript code (`decode_with_browser_hevc`) to perform the decoding. The javascript code will either return NV12 (YCbCr) or RGBA formatted data. NV12 is preferred if available.
In order to call the Javascript VideoDecoder API, 3 things are required:
* A ISO/IEC 14496-15 codec string (e.g. "hvc1.3.E.L93.B0")
* A binary serialized HEVCDecoderConfigurationRecord
* The image data (w/ VPS, SPS, PPS NAL unit stripped), prepended with 4 bytes describing the length
The codec string and HEVCDecoderConfigurationRecord are built from information in the NAL units that are pushed into the plugin. In the case of RGBA output, it is used directly (accounting for potentially differing strides), and …
=> Add a plugin based on WebCodecs (hardware decoding w/ webassembly)
